source:      .
destination: _deploy
config_url: http://beta.ocf.tw
# defaults:
#   - scope:
#       path: ""
#     values:
#       og_title: "test default title"
#       og_image: /mediakit/cover.png
#       og_description: "test default description"
