# 這個檔案用來存一些影響到全站的設定

# current
# 這個欄位用來設定網站當前年度，影響範圍包括
# 1.專案頁：判斷此專案是否為當年度，如果不是的話會
#   a.在專案名稱後面刮號加註年度
#   b.不顯示 call to action 按鈕
# 2.活動頁：判斷此活動是否為當年度，如果不是的話會
#   a.在活動名稱後面刮號加註年度
# 3.重新導向的頁面中 year 設定為 current 者
# 4.首頁進行中專案卡片的資料來自哪個年份
current: 2016

# menu
# 這個欄位用來設定主選單的選項與連結
menu:
  - title: 關於
    url: /about/
  - title: 工作夥伴
    url: /people/
  - title: 專案與成果
    url: /p/
  - title: 媒體專區
    url: /mediakit/
